# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2015

environment:
  matrix:
### MSVC Toolchains ###
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc
### GNU Toolchains ###
  # Stable 64-bit GNU
#    - channel: stable
#      target: x86_64-pc-windows-gnu
  # Beta 64-bit GNU
#    - channel: beta
#      target: x86_64-pc-windows-gnu
  # Nightly 64-bit GNU
#    - channel: nightly
#      target: x86_64-pc-windows-gnu

matrix:
  fast_finish: false
  allow_failures:
    - channel: nightly
    #- channel: beta

branches:
  only:
    - master

platform:
  - x64

install:
- ps: .\appveyor_rust_install.ps1

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false

# Uses 'cargo test' to run tests. Alternatively, the project may call compiled programs directly or
# perform other testing commands. Rust will automatically be placed in the PATH environment
# variable.
test_script:
# Installing PortAudio
#- curl -kLO https://github.com/adfernandes/precompiled-portaudio-windows/raw/master/portaudio-r1891-build.zip
#- 7z x portaudio-r1891-build.zip
- cmd: nuget install portaudio -OutputDirectory deps -ExcludeVersion
- cmd: set PATH=C:\projects\scaleless-music\deps\portaudio.redist\build\native\bin\x64\v120\Release;%PATH%
- cmd: set LIB=C:\projects\scaleless-music\deps\portaudio\build\native\lib\x64\v120\Release;%LIB%
- cmd: rename C:\projects\scaleless-music\deps\portaudio\build\native\lib\x64\v120\Release\portaudio_x64.lib portaudio.lib
#- cmd: set PORTAUDIO_ONLY_STATIC
- cmd: cargo test --features "be-portaudio" --verbose
